server:
  port: 80

#spring配置
spring:
  application:
    name: springcloud-consumer-dept

#Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-consumer-dept-80